### ISSUE TITLE
Contributions / Raw data

### ISSUE THREAD

**Issue by sexnine** [joyce-chen/persona5-negotiation#27]
Hey joyce-chen, I tried contacting you via email but the email wen't undelivered.

I was wondering whether you would be open to contributions?

I was thinking of implementing a feature where users could submit fixes or new additions to the negotiation questions right from the site.

I myself have found trouble with using the Google Form, as it's too much of a hassle to individually submit there, so I hope this feature could allow for more people to submit answers (myself included) with much less hassle to both the submitter and yourself.

If not, do you have the data in a format that I can use to make this on a separate site instead of using the MD files?  As I've noticed that data/ isn't up to date anymore and is now gitignored

Thanks :')

**Comment by joyce-chen** [comment]
Hey. Sorry for the late reply! My main email is out-of-date!

I've hadn't had time to update the negotiations or work on this thing in general. I have a more up-to-date source Excel sheet with all the info that I can push in the next couple of days. If you're still interested, a better submission tool is a much needed improvement to make this page self-sufficient. 

Please let me know what else you need!

**Comment by sexnine** [comment]
Haha, don't worry about it.  I would be very grateful if you could just upload the more up-to-date raw data (a .csv would be great)
If you don't really have the time to work on this, I would happily continue development and maintain this wonderful tool you have created.

Thanks :)

**Comment by joyce-chen** [comment]
@sexnine Sorry it took longer than I thought it would! I've updated the /data folder with the raw data of both the original and Royal questions in Excel files and the accompanying script that I've been using to convert the Excel data to html tables.
Both files are updated with the Google Form data I've received from last year til now. 

I'm working on a script to properly merge new data submitted from the Google Form. In terms of improving the submission process, I think I will stick with Google Form for the time being but I will reduce the amount of typing by adding all the questions and names in a dropdown menu. Hopefully that will be a good enough solution.

**Comment by sexnine** [comment]
Thanks @joyce-chen :)
