### ISSUE TITLE
Incubus can ask about 'ultimate move'

### ISSUE THREAD

**Issue by OleksiiDovhil** [joyce-chen/persona5-negotiation#4]
Question 'You have no idea I was about to use my ultimate move.' from timid
'...Try me.' is good one. 

same Persona. 'I coulda been a star...' - Are you giving up?  - good timid
'Try and rip it off me.' - 'Try and rip it off me.' - good timid

new question: 
'It's hard to tell under the mask, but... you're actually handsome, aren't you'
answers: 
'How did you know?' 
'No, not at all.' - good Timid
'I look OK, I guess.'

Question 'I'll go out with you just for today if there are no strings attached.'
'I've got enough on my plate...' - good Timid

new question: 
'...Maybe i'll call the police. Maybe i'll tell 'em tat you were worse than you actually were!' 
answers: 
'Call them. I dare you.'
'Please don't'
'It was self-defense.'

**Comment by joyce-chen** [comment]
I've added you results and new questions to the guide.
Thank you for your contribution!
